### ISSUE TITLE
USER STORY: Publish a poll

### ISSUE THREAD

**Issue by BekMart** [BekMart/love_running#4]
As an **administrator**, I can **publish a poll**, to **collect user feedback regarding the topic of running**.

### Acceptance Criteria:

- Acceptance Criteria 1: Poll must have several options
  
- Acceptance Criteria 2: Options should be provided as checkboxes
  
- Acceptance Criteria 3: Once submitted, feedback to be given to the user

### Tasks:

- [ ] Create poll with various options and design using HTML and CSS
- [ ] Add checkboxes to poll for user to select their choice
- [ ] Create feedback for when user completed poll
- [ ] Check functionality 

#2
