### ISSUE TITLE
USER STORY: Record poll results

### ISSUE THREAD

**Issue by BekMart** [BekMart/love_running#5]
As an **administrator**, I can **link the poll to a google spreadsheet**, so that **the results may be recorded**.

### Acceptance Criteria:

- Acceptance Criteria 1: All data must be relevant and accurate
  
- Acceptance Criteria 2: Spreadsheet should be clear to read and understand
  
- Acceptance Criteria 3: Spreadsheet to be updated immediately 

### Tasks:

- [ ] Create a google spreadsheet which is clear to read and has all necessary data present
- [ ] Link poll to google spreadsheet using API
- [ ] Test to ensure functionality
